import Typewriter from 'typewriter-effect/dist/core';

document.addEventListener(
  'DOMContentLoaded',
  () => {
    const typewriter = new Typewriter('#typewriter', { loop: true });
    typewriter
      .changeDeleteSpeed(50)
      .typeString("I'm a Software Engineer.")
      .pauseFor(1500)
      .deleteChars(18)
      .pauseFor(500)
      .typeString('CS Student.')
      .pauseFor(1500)
      .deleteChars(11)
      .pauseFor(500)
      .typeString('Amazon SDE Intern.')
      .pauseFor(1500)
      .deleteChars(18)
      .pauseFor(500)
      .typeString('Web Developer.')
      .pauseFor(1500)
      .deleteChars(14)
      .pauseFor(500)
      .typeString('Rustacean.')
      .pauseFor(1500)
      .deleteChars(10)
      .pauseFor(500)
      .typeString('Front End Engineer.')
      .pauseFor(1500)
      .deleteChars(19)
      .pauseFor(500)
      .typeString('GraphQL Enthusiast.')
      .pauseFor(1500)
      .deleteChars(19)
      .pauseFor(500)
      .typeString('Guitarist.')
      .pauseFor(1000)
      .deleteChars(10)
      .pauseFor(500)
      .typeString('Java Developer.')
      .pauseFor(1500)
      .deleteChars(15)
      .pauseFor(500)
      .typeString('Python Programmer.')
      .pauseFor(1500)
      .deleteChars(18)
      .pauseFor(500)
      .typeString('Cloud Engineer.')
      .pauseFor(1500)
      .deleteChars(15)
      .pauseFor(500)
      .typeString('Javascript Developer.')
      .pauseFor(1500)
      .deleteAll(35)
      .pauseFor(500)
      .start();
  },
  false
);
